// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Allow build-time Prisma generate even when platform doesn't inject env vars during image build.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
