// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const postgresFallbackUrl = "postgresql://postgres:postgres@localhost:5432/postgres";
const envDatabaseUrl = process.env["DATABASE_URL"];
const datasourceUrl =
  envDatabaseUrl && /^postgres(ql)?:\/\//i.test(envDatabaseUrl)
    ? envDatabaseUrl
    : postgresFallbackUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep Prisma generate/build working even if build-time DATABASE_URL is not injected.
    url: datasourceUrl,
  },
});
